# 50.039 Theory and Practice of Deep Learning Project 2024

Group 10
- Issac Jose Ignatius (1004999)
- Mahima Sharma (1006106)
- Dian Maisara (1006377)


### Import all relevant libraries

In [2]:
# Matplotlib
# import matplotlib.pyplot as plt
# from matplotlib.lines import Line2D
# Numpy
import numpy as np
# Pandas
import pandas as pd
# Torch
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torchvision
from torchvision.transforms import ToTensor
from torchvision.io import read_image
# TorchMetrics
from torchmetrics.classification import BinaryAccuracy

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
   ---------------------------------------- 0.0/179.2 kB ? eta -:--:--
   ------------- -------------------------- 61.4/179.2 kB 1.7 MB/s eta 0:00:01
   --------------------------- ------------ 122.9/179.2 kB 1.8 MB/s eta 0:00:01
   ---------------------------------------- 179.2/179.2 kB 1.8 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [7]:
print(torch.argmax(torch.tensor([[0,0,0]]), dim=1))
print(torch.argmax(torch.tensor([[1,0,0]]), dim=1))
print(torch.argmax(torch.tensor([[0,1,0]]), dim=1))
print(torch.argmax(torch.tensor([[0,0,1]]), dim=1))

tensor([0])
tensor([0])
tensor([1])
tensor([2])


## Motivation

Chest radiography is an essential diagnostic tool used in medical imaging to visualise structures and organs within the chest cavity. It is crucial for diagnosing various respiratory and heart-related conditions. However, with the increased demand for radiological reports within shorter timeframes to detect and treat illnesses, there have been insufficient radiologists available to perform such tasks at scale. Therefore, automated chest radiograph interpretation could provide substantial benefits supporting large-scale screening and population health initiatives. Deep-learning algorithms can be used to bridge this gap. They have been used for image classification, anomaly detection, organ segmentation, and disease progression prediction.
<br><br>

*In this project, we aim to train a deep neural network to perform multi-label image classification on a wide array of chest radiograph images that exhibit various pathologies.*<br><br>



---




## Data Exploration

The training and validation datasets are from the **CheXphoto dataset** (Philips et al., 2020). <br><br> CheXphoto comprises a training set of natural photos and synthetic transformations of 10,507 X-ray images from 3,000 unique patients (32,521 data points) sampled at random from the CheXpert training dataset and an accompanying validation set of natural and synthetic transformations applied to all 234 X-ray images from 200 patients with an additional 200 cell phone photos of x-ray films from another 200 unique patients (952 data points).

### DONT DELETE!!! Retrieving dataset from Google Cloud Storage (GCS)




In [ ]:
#OLD CODE : not in use as we are bringing in training datasets from notebook 1
# Connect to GCS to access data
#from google.colab import auth
#auth.authenticate_user() # TODO: everyone to send me gmail so I can have you authed for bucket access

#project_id = 'tpdl-414711'
#bucket_name = 'chexphoto-v1'
#!gcloud config set project {project_id}

# Install Cloud Storage FUSE.
#!echo "deb https://packages.cloud.google.com/apt gcsfuse-`lsb_release -c -s` main" | sudo tee /etc/apt/sources.list.d/gcsfuse.list
#!curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
#!apt -qq update && apt -qq install gcsfuse

# Mount a Cloud Storage bucket or location, without the gs:// prefix.
#mount_path = "chexphoto-v1"  # or a location like "my-bucket/path/to/mount"
#local_path = f"/mnt/gs/{mount_path}"

#!mkdir -p {local_path}
#!gcsfuse --implicit-dirs {mount_path} {local_path}

### Loading dataset (image and labels)

### If we need to do anything to the images (greymap conversion etc.), do it here (remove if N/A)

In [ ]:
# Create train, test and valid datasets using CheXDataset
# labels = [LOCAL_PATH +"/train.csv", LOCAL_PATH +"/test.csv", LOCAL_PATH +"/valid.csv"]
cheX_train_data = CheXDataset(train_df3) #CheXDataset(labels[0])
cheX_valid_data = CheXDataset(valid_df3) #CheXDataset(labels[2])

NameError: name 'train_df3' is not defined

## Model Tuning

### First iteration - Simple feedforward neural network

Maybe add a description here how the multi-head was implemented (with sources)

#### Model



In [ ]:
# Write out our base model here

#### Evaluation

Gradually, we moved the model into a traditional CNN-based architecture to see if we can surpass the performance from above. Briefly discuss what we needed to add to the model (filtering, convolution blablabla)

#### Model

#### Training

#### Evaluation

## Observations

**TODO** Discuss whether its right for us to pluck all our evaluation and training together and discuss it here or break up the code without any descriptions


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=d056a7b8-1929-4f43-a228-a643b0e765c5' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>